version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: unblock_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: unblock
    entrypoint:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --quiet) -eq 1
      interval: 10s
      start_period: 5s

  redis:
    image: redis:7.2-alpine
    container_name: unblock_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo_data:
  redis_data:
