services:
  mongodb:
    image: mongo:7.0
    container_name: unblock_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: unblock
    entrypoint:
      - mongod
      - --replSet
      - rs0
      - --bind_ip_all

  livekit:
    image: livekit/livekit-server:latest
    container_name: unblock_livekit
    restart: always
    command: --dev --bind 0.0.0.0
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"

volumes:
  mongo_data:
  redis_data:
